[tool.poetry]
name = "deep-person-reid"
version = "0.1.0"
description = ""
authors = ["Tim <tim@studiodiip.com>"]
readme = "README.md"
packages = [{include = "torchreid"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
