[build-system]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "torchreid"
version = "0.1.0"
description = "A library for deep learning person re-ID in PyTorch"
authors = ["Kaiyang Zhou <k.zhou@qmul.ac.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.19"
cython = "^0.29"
torch = "^1.8"

[tool.poetry.dev-dependencies]
pytest = "^5.1"

[tool.poetry.scripts]
torchreid = "torchreid.main:main"

[tool.poetry.extras]
docs = ["sphinx", "sphinx-rtd-theme"]
test = ["pytest"]

[tool.poetry.build]
requires = ["setuptools", "wheel", "Cython"]
build-backend = "setuptools.build_meta"